### PR TITLE
Group 6:Guide to PouchContainer(Exercise 1:cn,en)

### PR DESCRIPTION
**Pull request by LuvJia**
#22

### CODE REVIEW

**Comment by vanillasky0403** [comment]
Group 8:
'ubantu64bit安装'->'Ubuntu''

**Comment by XiaoYangMao827** [comment]
Group 8:
"slect continue,select 1024M for memory size"
spelling mistake

**Comment by AllaseYo33** [comment]
Group 2: 
The format need to be adjusted.

**Comment by Austinfjq** [comment]
Group2:
"Fork a repo to youre account from PouchContainer's github(https://github.com/alibaba/pouch)"
youre --> your

**Comment by zl117** [comment]
Comments from group 1:
  The format is different from what markdown requires. That is, for example, paragraphs should be separated.

**Pull request closed without merging**
